In [264]:
import warnings
warnings.filterwarnings('ignore')

In [265]:
corpus = "Hello my name raj. my nickname is Rudra and every know in parul as Rudra! I am last year student"

In [266]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [267]:
from nltk.tokenize import sent_tokenize

In [268]:
document = sent_tokenize(corpus)

In [269]:
document

['Hello my name raj.',
 'my nickname is Rudra and every know in parul as Rudra!',
 'I am last year student']

In [270]:
from nltk.tokenize import word_tokenize

In [271]:
word_tokenize(corpus)

['Hello',
 'my',
 'name',
 'raj',
 '.',
 'my',
 'nickname',
 'is',
 'Rudra',
 'and',
 'every',
 'know',
 'in',
 'parul',
 'as',
 'Rudra',
 '!',
 'I',
 'am',
 'last',
 'year',
 'student']

In [272]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [273]:
df = pd.read_csv("movies_metadata.csv", sep=',', engine='python', on_bad_lines='skip')

In [274]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [275]:
df.isnull().sum()

adult                         0
belongs_to_collection    298608
budget                        0
genres                        0
homepage                 295323
id                            0
imdb_id                      18
original_language            11
original_title                0
overview                    954
popularity                    5
poster_path                 386
production_companies          3
production_countries          4
release_date                 90
revenue                       9
runtime                     270
spoken_languages             11
status                       94
tagline                   25048
title                        15
video                        18
vote_average                 20
vote_count                   21
dtype: int64

In [276]:
df.duplicated().sum()

np.int64(17)

In [277]:
df = df.drop_duplicates().reset_index(drop=True)

In [278]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [279]:
df = df[['title','overview','genres','tagline','vote_average','popularity']]

In [280]:
df

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,8.387519
...,...,...,...,...,...,...
303078,Flight of Labyrinth Awakening,"In a high-stakes world of deception and crime,...","[{'id': 878, 'name': 'Science Fiction'}, {'id'...","Beyond boundaries, beyond fear.",6.3,4.223
303079,Whispering Phoenix Ascension,"When a secret experiment goes wrong, an unlike...","[{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'na...",Out of darkness comes light.,7.0,7.716
303080,Code Name: Horizon Invasion,"An emotional journey exploring love, family bo...","[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",Trust no one. Fear everything.,7.7,1.029
303081,Mission: Chaser Endgame,"As unexpected events unfold, heroes rise from ...","[{'id': 878, 'name': 'Science Fiction'}, {'id'...",Trust no one. Fear everything.,7.1,0.242
303082,Blood and Galaxy Origins,A stunning epic taking viewers through breatht...,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",Truth is the ultimate weapon.,5.8,0.653

In [281]:
df.isnull().sum()

title              15
overview          954
genres              0
tagline         25036
vote_average       20
popularity          5
dtype: int64

In [282]:
df = df.dropna(subset=['title'])

In [283]:
df['overview']=df['overview'].fillna('')

In [284]:
import ast
df['genres']=df['genres'].apply(lambda x: ' '.join([i['name'] for i in ast.literal_eval(x)]))

In [285]:
df['tagline']=df['tagline'].fillna('')

In [286]:
df['vote_average']=df['vote_average'].fillna(df['vote_average'].mean())

In [287]:
df['popularity']=df['popularity'].fillna(df['popularity'].mode())

In [288]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [289]:
df['tags']=df['overview']+df['genres']+df['tagline']

In [290]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [291]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [292]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [293]:
import re
def preprocess(text):
    text = str(text).lower()
    text = re.sub(r'[^\w\s]', ' ', text)
    words = text.split()
    words = [word for word in words if word not in stop_words]
    words = [lemmatizer.lemmatize(word) for word in words]
    return ' '.join(words)

In [294]:
df['tags'] = df['tags'].apply(preprocess)

In [295]:
df['tags'][0]

'led woody andy toy live happily room andy birthday brings buzz lightyear onto scene afraid losing place andy heart woody plot buzz circumstance separate buzz woody owner duo eventually learns put aside difference animation comedy family'

In [296]:
df = df.reset_index(drop=True)

In [297]:
indices = pd.Series(df.index, index=df['title']).drop_duplicates()

In [298]:
indices

title
Toy Story                             0
Jumanji                               1
Grumpier Old Men                      2
Waiting to Exhale                     3
Father of the Bride Part II           4
                                  ...
Flight of Labyrinth Awakening    303063
Whispering Phoenix Ascension     303064
Code Name: Horizon Invasion      303065
Mission: Chaser Endgame          303066
Blood and Galaxy Origins         303067
Length: 303068, dtype: int64

In [299]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [300]:
tfidf = TfidfVectorizer(max_features=500000,ngram_range=(1,2),stop_words='english')

In [301]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [302]:
tfidf_matrix.shape

(303068, 500000)

In [303]:
from sklearn.metrics.pairwise import linear_kernel

In [304]:
def recommend(title,n=10):
  if title not in indices:
    return ['Movie not found']
  idx = indices[title]
  sim_scores = linear_kernel(tfidf_matrix[idx],tfidf_matrix).flatten()
  similars_idx = sim_scores.argsort()[::-1][1:n+1]
  return df['title'].iloc[similars_idx]

In [306]:
recommend('SpederMan')

['Movie not found']

In [305]:
import pickle
pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))
pickle.dump(tfidf,open('tfidf.pkl','wb'))
df.to_pickle('df.pkl')
pickle.dump(indices,open('indices.pkl','wb'))